### PR TITLE
bump quarkus to next LTS

### PR DESCRIPTION
**Pull request by rmanibus**

### CODE REVIEW

**Comment by rmanibus** [comment]
@melloware are we ok using the new LTS in this project ?

**Comment by melloware** [comment]
yes absolutely.  We also have to make a couple of other fixes for doc generation.  It changed in 3.15.

**Comment by melloware** [comment]
I just committed the fixes to your branch

**Comment by rmanibus** [comment]
Perfect thank you ! Is it ready to be merged ?

**Pull request merged**
