### PR TITLE
Fix #116: Update OTEL docs for GRPC

### LINKED ISSUE #116: otel disable is buggy
It seems like the property `quarkus.temporal.telemetry.enabled=false` does not works

Context: #71 

The devservice is working, but when the extension `quarkus-opentelemetry` is in the pom, there is some errors in the logs:

```
2024-10-23 00:49:41,947 SEVERE [io.qua.ope.run.exp.otl.VertxGrpcExporter] (vert.x-eventloop-thread-5) Failed to export spans. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
2024-10-23 00:49:47,813 SEVERE [io.qua.ope.run.exp.otl.VertxGrpcExporter] (vert.x-eventloop-thread-5) Failed to export spans. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
```

When i try to disable the otel programaticaly or by properties, the result is the same.
But when the extension is not present, it works fine.

to reproduce the issue:

1. clone fork <https://github.com/ggrebert/quarkus-temporal/tree/17-devservice> (branch 17-derservice)
2. run the command `mvn -am -pl integration-tests/devservice quarkus:dev`
3. open the temporal UI in the dev-ui

### PR DESCRIPTION
**Pull request by melloware**
Fix #116: Update OTEL docs for GRPC

### CODE REVIEW

**Comment by ggrebert** [comment]
issue still persist but differently after rebasing from main branch and adding the following properties:

```properties
quarkus.otel.instrument.grpc=false
quarkus.temporal.telemetry.enabled=false
```

Before the log was **SEVERE**, now it's a **WARNING**:

* before

    ```
    2024-10-23 00:49:41,947 SEVERE [io.qua.ope.run.exp.otl.VertxGrpcExporter] (vert.x-eventloop-thread-5) Failed to export spans. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
    2024-10-23 00:49:47,813 SEVERE [io.qua.ope.run.exp.otl.VertxGrpcExporter] (vert.x-eventloop-thread-5) Failed to export spans. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
    ```

* after

    ```
    2024-10-24 09:49:00,253 WARNING [io.qua.ope.run.exp.otl.sen.VertxGrpcSender] (vert.x-eventloop-thread-5) Failed to export TraceRequestMarshalers. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
    2024-10-24 09:49:00,255 WARNING [io.ope.exp.int.grp.GrpcExporter] (vert.x-eventloop-thread-5) Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to export TraceRequestMarshalers. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
    2024-10-24 09:49:06,204 WARNING [io.qua.ope.run.exp.otl.sen.VertxGrpcSender] (vert.x-eventloop-thread-5) Failed to export TraceRequestMarshalers. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
    2024-10-24 09:49:06,205 WARNING [io.ope.exp.int.grp.GrpcExporter] (vert.x-eventloop-thread-5) Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to export TraceRequestMarshalers. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
    ```

**Comment by melloware** [comment]
OK so these are definitely coming from Quarkus GRPC let me see if there is any other way to turn them off

**Comment by melloware** [comment]
OK got it. 

```
quarkus.temporal.telemetry.enabled=false
quarkus.otel.instrument.grpc=false
quarkus.otel.instrument.vertx-http=false
```

Vert.X was also instrumented as soon as it seens the OpenTelemetry JAR.

**Comment by ggrebert** [comment]
works fine

**Pull request merged**
